version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-tracker-app
    ports:
      - "3000:3000" 
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/telegramBot 
    depends_on:
      - mongodb
    volumes:
      - .:/app 
      - /app/node_modules 

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
